# Recitation 0 - Introduction
Welcome to the Recitation 0 for the Fall 2020 iteration of the course 11-785: Intro to Deep Learning. 
Recitation 0 is split into 3 bigger pictures, with every part divided into sub-parts. 
* Big Picture 1 (Recitation 0A, 0B, 0C) - Introduction to Python, Numpy, and Pytorch
* Big Picture 2 (Recitation 0D, 0E)     - Introduction to AWS, Google Colab, and Jupyter
* Big Picture 3 (Recitation 0F, 0G)     - Introduction to Debugging, Tensorboard, TSNE, and Visualization


# *Recitation 0A - Introduction to Python*



Python

All information about python, from downloading to documentation, can be found here: https://www.python.org. We recommend that you use python 3 for the homeworks in this course.

External Modules

Install external modules using the pip package manager(https://pypi.org/project/pip/). 
The main modules we'll be using in the course include  

*   numpy
*   torch (Pytorch)

To check if both the modules got installed correctly, please type the below code in your terminal and check if some version comes up.

```
python -c "import torch; print(torch.__version__)"
python -c "import numpy; print(numpy.version.version)"
```



Importing Modules code snippets

In [ ]:
import numpy
a = numpy.array([1,2,3])

import numpy as np
a = np.array([1,2,3])

from math import ceil

from math import * 

File Formats and Loading Data



*   .txt: plain text file
*   .pkl: python objects
*   .csv: tabular data - fields separated by commas
*   .npy: numpy arrays (saved using numpy library)
*   .npz: zipped archive of npy files

In [ ]:
# Download recitation 0a.txt into google colab local VM
!wget https://raw.githubusercontent.com/cheul0518/CMU11-785/main/rec0/recitation0a.txt

# traditional way of reading files with explicit open and close statements

f = open("recitation0a.txt", "r")
print(f.readlines())
f.close()

['This is the first line of text.\n', 'This is the second line of text.']


In [ ]:
# no need to mention explict close statement in the "with" statement

with open("recitation0a.txt", "r") as f:
    print(f.readlines())

['This is the first line of text.\n', 'This is the second line of text.']


More about file access modes: https://stackoverflow.com/questions/16208206/confused-by-python-file-mode-w

Diagram: [diagram](https://stackoverflow.com/a/30566011)

In [12]:
# Download sampledata.csv into google colab local VM
!wget https://raw.githubusercontent.com/cheul0518/CMU11-785/main/rec0/sampledata.csv

# to read a csv file

import csv

with open ("sampledata.csv", "r") as f:
    reader = csv.reader(f, delimiter=",")
    
    for row in reader:
        print(row)

--2020-11-24 23:44:47--  https://raw.githubusercontent.com/cheul0518/CMU11-785/main/rec0/sampledata.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 889 [text/plain]
Saving to: ‘sampledata.csv.1’

sampledata.csv.1    100%[===================>]     889  --.-KB/s    in 0s      

2020-11-24 23:44:47 (43.6 MB/s) - ‘sampledata.csv.1’ saved [889/889]

['Year', 'Variable_name', 'Variable_category', 'Value']
['2018', 'Total income', 'Financial performance', '691859']
['2018', 'Sales, government funding, grants and subsidies', 'Financial performance', '605766']
['2018', 'Interest, dividends and donations', 'Financial performance', '63509']
['2018', 'Non-operating income', 'Financial performance', '22583']
['2018', 'Total expenditure', 'Financial performance', '597623']

In [13]:
import pickle

mydict = {"student1": "Alice", "Student2": "Bob", "Student3": "Rachel"}

pickle.dump(mydict, open("store.pkl", "wb"))

loaded = pickle.load(open("store.pkl", "rb"))
print(loaded)

{'student1': 'Alice', 'Student2': 'Bob', 'Student3': 'Rachel'}


Data Storing


 - lists: generic container - allow for numeric indexing
 - tuples: immutable lists
 - dictionaries: keys act as indices - keys must be unique
 - sets: group of unique elements

In [24]:
same_type_list = [1, 3, 4, 89, 23, 43, 90]
diff_type_list = [1, 3, "hello", 4.9, "c"]

print(same_type_list[3])
print(len(same_type_list))

same_type_list[0] = "I'm new"
print(same_type_list)

89
7
["I'm new", 3, 4, 89, 23, 43, 90]


In [16]:
new_list = same_type_list + diff_type_list  # + sign does combine (concatante)
print(new_list)

[1, 3, 4, 89, 23, 43, 90, 1, 3, 'hello', 4.9, 'c']


In [17]:
new_list_2 = ["hi", "hello"] * 2
print(new_list_2)

['hi', 'hello', 'hi', 'hello']


In [20]:
same_type_tuple = (1, 10, 7)
diff_type_tuple = (1, 2, "foo") 

print(diff_type_tuple[2])
print(same_type_tuple[1])

#same_type_tuple[0] = 3

foo
10


In [25]:
# some more list/tuple functions: assumtpion: all items in the list are the same type

print(max(same_type_tuple))
print(min(same_type_tuple))
print(sorted(same_type_tuple))

#print(sorted(diff_type_tuple))
#print(min(same_type_list))

10
1
[1, 7, 10]


TypeError: ignored

In [30]:
my_dict = {"student1": "Alice", "student2": "Bob", "student3": "Rachel"}  # key : value

print(my_dict["student1"])
#print(my_dict[0])
#print(my_dict["student4"])
print(my_dict.get("student3", "student does not exist"))
print(my_dict.get("student4", "student does not exist"))

Alice
Rachel
student does not exist


In [31]:
my_dict["student1"] = "Billy"
print(my_dict)

{'student1': 'Billy', 'student2': 'Bob', 'student3': 'Rachel'}


In [35]:
my_set = {"obj1", "obj2", "obj3"} # key (no value)
print(my_set)
#print(my_set[1])
#print(my_set["obj1"])

{'obj1', 'obj2', 'obj3'}


In [39]:
# use of random in selecting data from dictionaries

import random
countries = {'VENEZUELA':'CARACAS', 'CANADA':'OTTAWA'}
bex = random.choice(list(countries))
print(bex)

VENEZUELA


More about Random: https://docs.python.org/3/library/random.html

In [47]:
some_array = [[[64,64,32],
                 [22,23,24]],
                [[64,4,32],
                 [22,3,24]]
               ]
some_array = np.asarray(some_array)
print(some_array.shape)

another_array = list(range(3))
print(another_array)

(2, 2, 3)
[0, 1, 2]


Filtering Lists

1. Slicing and Dicing
2. List comprehensions

In [ ]:
# slicing & dicing
# general format: sliced_list = [start_idx : end_idx+1 : step]

some_list = [2, 5, 2, 45, 7, 9, 76, 80, 21, 53]
print(some_list[5:])
print(some_list[:3])
print(some_list[3:9:2])

[9, 76, 80, 21, 53]
[2, 5, 2]
[45, 9, 80]


Slicing with 2D and 3D arrays

3D arrays are indexed across the 3 dimensions as follows:

![3D array](https://raw.githubusercontent.com/cheul0518/CMU11-785/main/rec0/3d-array-stack.png)

Where if you consider your 3D array to be a stack of matrices, i selects the matrix, j selects the row in that matrix and k selects the column in that matrix.

In [48]:
# slicing 3D array examples:

three_d_array = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

print(three_d_array)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [50]:
# ------------ selecting a row ------------
# you want to specify the matrix, then the row

print(three_d_array[0,2]) # matrix 0, row 2
print(three_d_array[0:2])

[16 17 18]
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


In [51]:
# ------------ selecting a column ------------
# you want to specify the matrix, ignore the row, and then specify the column

print(three_d_array[1, :, 1]) # matrix 1, column 1

[21 24 27]


In [52]:
# ------------ selecting a matrix ------------

print(three_d_array[2]) # matrix 2

[[30 31 32]
 [33 34 35]
 [36 37 38]]


In [53]:
# ------------ creating a row across matrices ------------
print(three_d_array[:, 1, 2]) # for every matrix, row 1, column 2 

[15 25 35]


In [54]:
# ------------ creating a matrix from rows ------------
print(three_d_array[:, 1]) # for every matrix, row 1

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [55]:
# ------------ creating a matrix from columns ------------
print(three_d_array[:, :, 1]) # for every matrix, for every row, column 1

[[11 14 17]
 [21 24 27]
 [31 34 37]]


You can also slice within rows, columns and matrices in a 3D array, the same way you would in 1D arrays.

In [56]:
# list comprehensions
# general format: new_list = [expression for_loop_one_or_more condtions]

res = [num for num in same_type_list if isinstance(num, int) and num>0]
print(res)

[3, 4, 89, 23, 43, 90]


In [57]:
%%timeit 

res2 = []
res2 = [i for i in range(500)]

100000 loops, best of 3: 15.4 µs per loop


In [58]:
%%timeit

res3 = []
for i in range(500):
    res3.append(i)

10000 loops, best of 3: 32.7 µs per loop


# Classes

You'll use classes extensively in the homeworks in this course. You will need classes for defining your models as well as your datasets. We'll consider an example of implementing the dataset class here.

In [ ]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __getitem__(self, index):    
        return (self.x[index], self.y[index])
    
    def __len__(self):
        return len(self.x) 

# Debugging

You'll be extensively using pdb for debugging across the entire semester, especially in Part 2s. Few useful debugging shortcuts:

* n - next statement (excludes function calls)
* s - step into (includes function calls)
* q - quit
* b - breakpoints

You can read more about pdb and its commands here https://docs.python.org/3/library/pdb.html

In [61]:
# notice the use of "n", "s", "c" when pdb sets the trace. 
# If "s" is commanded, it would go inside the set_trace() method
# If you need to step out, just command "c"

import pdb

for i in range(3):
    pdb.set_trace()
    print("this is iteration " + str(i))

> <ipython-input-61-799b99dfe470>(9)<module>()
-> print("this is iteration " + str(i))
(Pdb) n
this is iteration 0
> <ipython-input-61-799b99dfe470>(7)<module>()
-> for i in range(3):
(Pdb) n
> <ipython-input-61-799b99dfe470>(8)<module>()
-> pdb.set_trace()
(Pdb) n
> <ipython-input-61-799b99dfe470>(9)<module>()
-> print("this is iteration " + str(i))
(Pdb) n
this is iteration 1
> <ipython-input-61-799b99dfe470>(7)<module>()
-> for i in range(3):
(Pdb) n
> <ipython-input-61-799b99dfe470>(8)<module>()
-> pdb.set_trace()
(Pdb) n
> <ipython-input-61-799b99dfe470>(9)<module>()
-> print("this is iteration " + str(i))
(Pdb) q


BdbQuit: ignored